# Generated by Django 3.2.18 on 2023-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmain',
            old_name='models',
            new_name='model',
        ),
    ]
